typography_spectrum: 0
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: Wolf & the Gang
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: c0f8811b-5ce9-425c-bf82-d33366768755
    type: content
favicon: null
title: We are  a Family of 4
purpose: []
