typography_spectrum: 0.2421359547879547
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.7570110822562128
  lightness: 0.8448354101274163
  saturation: 0.5539908341597766
  rhythmicContrast: 0.5927247628569603
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7881991821341217
analytics:
  google: null
  facebook: null
  twitter: null
name: Wolf & the Gang
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: c0f8811b-5ce9-425c-bf82-d33366768755
    type: content
  - name: Blog
    id: f4bb934f-50a8-4129-bc53-68937e9303d2
    type: content
favicon: null
title: We are a Family of 4
description: simply by the Grace of God
purpose: []
